### ISSUE TITLE
vertices_dll problems unreal engine 5.1

### ISSUE THREAD

**Issue by maxshosha** [Wisdom-Labs/Algorand-Unreal-Engine-SDK#4]
Using windows and compiling the plugin with unreal 5.1 project giving errors with the vertices.dll files.
I saw it was updated. But still not working
 https://github.com/Wisdom-Labs/Algorand-Unreal-Engine-SDK/commit/a31fb6e50d12ce5e92ea62e63561ca42a45e8a0d

**Comment by OnlyDragon0403** [comment]
- [x] added the 3rd party library to Vertices.Build.cs
- [x] fixed bugs related to length limitation of folder path.
