### ISSUE TITLE
Multiply Vertices errors in Unreal 5.1

### ISSUE THREAD

**Issue by maxshosha** [Wisdom-Labs/Algorand-Unreal-Engine-SDK#7]
Whiel executing a payment transaction the following errors are showing up which proceed to fail the transaction:

Vertices sodium_init err_code 1
Vertices new err_code 0
Vertices ping err_code 1

Errors occur while using RPC data from Purestack and Algoexplorer API
![error code](https://user-images.githubusercontent.com/96133925/219311091-0b672df6-d3ec-4a1d-9206-7049ca4716da.PNG)

**Comment by OnlyDragon0403** [comment]
Thank you for your comment.
Let me know the rpc data you entered when you use purestake api.
For ex,  
- rpc url : `https://testnet-algorand.api.purestake.io/ps2`
- rpc port: `0`
- rpc token Header: `x-api-key:bLcs4F2SyGY0InF9M6Vl9piFTIZ8Ww281OjKXyE1`

Have you tried like this?

**Comment by maxshosha** [comment]
I have filled once again the information you have shared. Still the same issue is occuring

**Comment by maxshosha** [comment]
The following data is used:

rpc url : https://testnet-algorand.api.purestake.io/ps2
rpc port: 0
rpc token Header: x-api-key:bLcs4F2SyGY0InF9M6Vl9piFTIZ8Ww281OjKXyE1

**Comment by maxshosha** [comment]
It is fixed
